//go:build !ignore_autogenerated
// +build !ignore_autogenerated

/*
Copyright 2023.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AfxdpNetwork) DeepCopyInto(out *AfxdpNetwork) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	out.Status = in.Status
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AfxdpNetwork.
func (in *AfxdpNetwork) DeepCopy() *AfxdpNetwork {
	if in == nil {
		return nil
	}
	out := new(AfxdpNetwork)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *AfxdpNetwork) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AfxdpNetworkList) DeepCopyInto(out *AfxdpNetworkList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]AfxdpNetwork, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AfxdpNetworkList.
func (in *AfxdpNetworkList) DeepCopy() *AfxdpNetworkList {
	if in == nil {
		return nil
	}
	out := new(AfxdpNetworkList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *AfxdpNetworkList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AfxdpNetworkNicSelector) DeepCopyInto(out *AfxdpNetworkNicSelector) {
	*out = *in
	if in.Drivers != nil {
		in, out := &in.Drivers, &out.Drivers
		*out = make([]*AfxdpNetworkPoolDriver, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(AfxdpNetworkPoolDriver)
				(*in).DeepCopyInto(*out)
			}
		}
	}
	if in.Devices != nil {
		in, out := &in.Devices, &out.Devices
		*out = make([]*AfxdpNetworkPoolDevice, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(AfxdpNetworkPoolDevice)
				**out = **in
			}
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AfxdpNetworkNicSelector.
func (in *AfxdpNetworkNicSelector) DeepCopy() *AfxdpNetworkNicSelector {
	if in == nil {
		return nil
	}
	out := new(AfxdpNetworkNicSelector)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AfxdpNetworkNodePolicy) DeepCopyInto(out *AfxdpNetworkNodePolicy) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	out.Status = in.Status
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AfxdpNetworkNodePolicy.
func (in *AfxdpNetworkNodePolicy) DeepCopy() *AfxdpNetworkNodePolicy {
	if in == nil {
		return nil
	}
	out := new(AfxdpNetworkNodePolicy)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *AfxdpNetworkNodePolicy) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AfxdpNetworkNodePolicyList) DeepCopyInto(out *AfxdpNetworkNodePolicyList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]AfxdpNetworkNodePolicy, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AfxdpNetworkNodePolicyList.
func (in *AfxdpNetworkNodePolicyList) DeepCopy() *AfxdpNetworkNodePolicyList {
	if in == nil {
		return nil
	}
	out := new(AfxdpNetworkNodePolicyList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *AfxdpNetworkNodePolicyList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AfxdpNetworkNodePolicySpec) DeepCopyInto(out *AfxdpNetworkNodePolicySpec) {
	*out = *in
	if in.NodeSelector != nil {
		in, out := &in.NodeSelector, &out.NodeSelector
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	if in.Pools != nil {
		in, out := &in.Pools, &out.Pools
		*out = make([]*AfxdpNetworkPool, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(AfxdpNetworkPool)
				(*in).DeepCopyInto(*out)
			}
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AfxdpNetworkNodePolicySpec.
func (in *AfxdpNetworkNodePolicySpec) DeepCopy() *AfxdpNetworkNodePolicySpec {
	if in == nil {
		return nil
	}
	out := new(AfxdpNetworkNodePolicySpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AfxdpNetworkNodePolicyStatus) DeepCopyInto(out *AfxdpNetworkNodePolicyStatus) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AfxdpNetworkNodePolicyStatus.
func (in *AfxdpNetworkNodePolicyStatus) DeepCopy() *AfxdpNetworkNodePolicyStatus {
	if in == nil {
		return nil
	}
	out := new(AfxdpNetworkNodePolicyStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AfxdpNetworkNodeState) DeepCopyInto(out *AfxdpNetworkNodeState) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AfxdpNetworkNodeState.
func (in *AfxdpNetworkNodeState) DeepCopy() *AfxdpNetworkNodeState {
	if in == nil {
		return nil
	}
	out := new(AfxdpNetworkNodeState)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *AfxdpNetworkNodeState) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AfxdpNetworkNodeStateList) DeepCopyInto(out *AfxdpNetworkNodeStateList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]AfxdpNetworkNodeState, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AfxdpNetworkNodeStateList.
func (in *AfxdpNetworkNodeStateList) DeepCopy() *AfxdpNetworkNodeStateList {
	if in == nil {
		return nil
	}
	out := new(AfxdpNetworkNodeStateList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *AfxdpNetworkNodeStateList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AfxdpNetworkNodeStateSpec) DeepCopyInto(out *AfxdpNetworkNodeStateSpec) {
	*out = *in
	if in.Interfaces != nil {
		in, out := &in.Interfaces, &out.Interfaces
		*out = make(Interfaces, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AfxdpNetworkNodeStateSpec.
func (in *AfxdpNetworkNodeStateSpec) DeepCopy() *AfxdpNetworkNodeStateSpec {
	if in == nil {
		return nil
	}
	out := new(AfxdpNetworkNodeStateSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AfxdpNetworkNodeStateStatus) DeepCopyInto(out *AfxdpNetworkNodeStateStatus) {
	*out = *in
	if in.Interfaces != nil {
		in, out := &in.Interfaces, &out.Interfaces
		*out = make(InterfaceExts, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AfxdpNetworkNodeStateStatus.
func (in *AfxdpNetworkNodeStateStatus) DeepCopy() *AfxdpNetworkNodeStateStatus {
	if in == nil {
		return nil
	}
	out := new(AfxdpNetworkNodeStateStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AfxdpNetworkPool) DeepCopyInto(out *AfxdpNetworkPool) {
	*out = *in
	in.NicSelector.DeepCopyInto(&out.NicSelector)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AfxdpNetworkPool.
func (in *AfxdpNetworkPool) DeepCopy() *AfxdpNetworkPool {
	if in == nil {
		return nil
	}
	out := new(AfxdpNetworkPool)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AfxdpNetworkPoolDevice) DeepCopyInto(out *AfxdpNetworkPoolDevice) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AfxdpNetworkPoolDevice.
func (in *AfxdpNetworkPoolDevice) DeepCopy() *AfxdpNetworkPoolDevice {
	if in == nil {
		return nil
	}
	out := new(AfxdpNetworkPoolDevice)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AfxdpNetworkPoolDriver) DeepCopyInto(out *AfxdpNetworkPoolDriver) {
	*out = *in
	if in.ExcludeDevices != nil {
		in, out := &in.ExcludeDevices, &out.ExcludeDevices
		*out = make([]*AfxdpNetworkPoolDevice, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(AfxdpNetworkPoolDevice)
				**out = **in
			}
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AfxdpNetworkPoolDriver.
func (in *AfxdpNetworkPoolDriver) DeepCopy() *AfxdpNetworkPoolDriver {
	if in == nil {
		return nil
	}
	out := new(AfxdpNetworkPoolDriver)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AfxdpNetworkSpec) DeepCopyInto(out *AfxdpNetworkSpec) {
	*out = *in
	if in.EthtoolCmds != nil {
		in, out := &in.EthtoolCmds, &out.EthtoolCmds
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AfxdpNetworkSpec.
func (in *AfxdpNetworkSpec) DeepCopy() *AfxdpNetworkSpec {
	if in == nil {
		return nil
	}
	out := new(AfxdpNetworkSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AfxdpNetworkStatus) DeepCopyInto(out *AfxdpNetworkStatus) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AfxdpNetworkStatus.
func (in *AfxdpNetworkStatus) DeepCopy() *AfxdpNetworkStatus {
	if in == nil {
		return nil
	}
	out := new(AfxdpNetworkStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AfxdpOperatorConfig) DeepCopyInto(out *AfxdpOperatorConfig) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	out.Status = in.Status
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AfxdpOperatorConfig.
func (in *AfxdpOperatorConfig) DeepCopy() *AfxdpOperatorConfig {
	if in == nil {
		return nil
	}
	out := new(AfxdpOperatorConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *AfxdpOperatorConfig) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AfxdpOperatorConfigList) DeepCopyInto(out *AfxdpOperatorConfigList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]AfxdpOperatorConfig, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AfxdpOperatorConfigList.
func (in *AfxdpOperatorConfigList) DeepCopy() *AfxdpOperatorConfigList {
	if in == nil {
		return nil
	}
	out := new(AfxdpOperatorConfigList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *AfxdpOperatorConfigList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AfxdpOperatorConfigSpec) DeepCopyInto(out *AfxdpOperatorConfigSpec) {
	*out = *in
	if in.ConfigDaemonNodeSelector != nil {
		in, out := &in.ConfigDaemonNodeSelector, &out.ConfigDaemonNodeSelector
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	if in.EnableInjector != nil {
		in, out := &in.EnableInjector, &out.EnableInjector
		*out = new(bool)
		**out = **in
	}
	if in.EnableOperatorWebhook != nil {
		in, out := &in.EnableOperatorWebhook, &out.EnableOperatorWebhook
		*out = new(bool)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AfxdpOperatorConfigSpec.
func (in *AfxdpOperatorConfigSpec) DeepCopy() *AfxdpOperatorConfigSpec {
	if in == nil {
		return nil
	}
	out := new(AfxdpOperatorConfigSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AfxdpOperatorConfigStatus) DeepCopyInto(out *AfxdpOperatorConfigStatus) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AfxdpOperatorConfigStatus.
func (in *AfxdpOperatorConfigStatus) DeepCopy() *AfxdpOperatorConfigStatus {
	if in == nil {
		return nil
	}
	out := new(AfxdpOperatorConfigStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Interface) DeepCopyInto(out *Interface) {
	*out = *in
	if in.SubFunctions != nil {
		in, out := &in.SubFunctions, &out.SubFunctions
		*out = make([]SubFunction, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Interface.
func (in *Interface) DeepCopy() *Interface {
	if in == nil {
		return nil
	}
	out := new(Interface)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *InterfaceExt) DeepCopyInto(out *InterfaceExt) {
	*out = *in
	if in.SFs != nil {
		in, out := &in.SFs, &out.SFs
		*out = make([]SubFunction, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new InterfaceExt.
func (in *InterfaceExt) DeepCopy() *InterfaceExt {
	if in == nil {
		return nil
	}
	out := new(InterfaceExt)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in InterfaceExts) DeepCopyInto(out *InterfaceExts) {
	{
		in := &in
		*out = make(InterfaceExts, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new InterfaceExts.
func (in InterfaceExts) DeepCopy() InterfaceExts {
	if in == nil {
		return nil
	}
	out := new(InterfaceExts)
	in.DeepCopyInto(out)
	return *out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in Interfaces) DeepCopyInto(out *Interfaces) {
	{
		in := &in
		*out = make(Interfaces, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Interfaces.
func (in Interfaces) DeepCopy() Interfaces {
	if in == nil {
		return nil
	}
	out := new(Interfaces)
	in.DeepCopyInto(out)
	return *out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SubFunction) DeepCopyInto(out *SubFunction) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SubFunction.
func (in *SubFunction) DeepCopy() *SubFunction {
	if in == nil {
		return nil
	}
	out := new(SubFunction)
	in.DeepCopyInto(out)
	return out
}
